'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute()>

Namespace RiaServicesMailMerge.Web
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class AdventureWorksEntities
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new AdventureWorksEntities object using the connection string found in the 'AdventureWorksEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=AdventureWorksEntities", "AdventureWorksEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new AdventureWorksEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "AdventureWorksEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new AdventureWorksEntities object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "AdventureWorksEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property vEmployees() As ObjectSet(Of vEmployee)
			Get
				If (_vEmployees Is Nothing) Then
					_vEmployees = MyBase.CreateObjectSet(Of vEmployee)("vEmployees")
				End If
				Return _vEmployees
			End Get
		End Property
		Private _vEmployees As ObjectSet(Of vEmployee)

		#End Region
		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the vEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddTovEmployees(ByVal vEmployee As vEmployee)
			MyBase.AddObject("vEmployees", vEmployee)
		End Sub

		#End Region
	End Class


	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksModel", Name:="vEmployee"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class vEmployee
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new vEmployee object.
		''' </summary>
		''' <param name="employeeID">Initial value of the EmployeeID property.</param>
		''' <param name="firstName">Initial value of the FirstName property.</param>
		''' <param name="lastName">Initial value of the LastName property.</param>
		''' <param name="jobTitle">Initial value of the JobTitle property.</param>
		''' <param name="emailPromotion">Initial value of the EmailPromotion property.</param>
		''' <param name="addressLine1">Initial value of the AddressLine1 property.</param>
		''' <param name="city">Initial value of the City property.</param>
		''' <param name="stateProvinceName">Initial value of the StateProvinceName property.</param>
		''' <param name="postalCode">Initial value of the PostalCode property.</param>
		''' <param name="countryRegionName">Initial value of the CountryRegionName property.</param>
		Public Shared Function CreatevEmployee(ByVal employeeID As Global.System.Int32, ByVal firstName As Global.System.String, ByVal lastName As Global.System.String, ByVal jobTitle As Global.System.String, ByVal emailPromotion As Global.System.Int32, ByVal addressLine1 As Global.System.String, ByVal city As Global.System.String, ByVal stateProvinceName As Global.System.String, ByVal postalCode As Global.System.String, ByVal countryRegionName As Global.System.String) As vEmployee
			Dim vEmployee As New vEmployee()
			vEmployee.EmployeeID = employeeID
			vEmployee.FirstName = firstName
			vEmployee.LastName = lastName
			vEmployee.JobTitle = jobTitle
			vEmployee.EmailPromotion = emailPromotion
			vEmployee.AddressLine1 = addressLine1
			vEmployee.City = city
			vEmployee.StateProvinceName = stateProvinceName
			vEmployee.PostalCode = postalCode
			vEmployee.CountryRegionName = countryRegionName
			Return vEmployee
		End Function

		#End Region
		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property EmployeeID() As Global.System.Int32
			Get
				Return _EmployeeID
			End Get
			Set(ByVal value As System.Int32)
				If _EmployeeID <> value Then
					OnEmployeeIDChanging(value)
					ReportPropertyChanging("EmployeeID")
					_EmployeeID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("EmployeeID")
					OnEmployeeIDChanged()
				End If
			End Set
		End Property
		Private _EmployeeID As Global.System.Int32
		Partial Private Sub OnEmployeeIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnEmployeeIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Title() As Global.System.String
			Get
				Return _Title
			End Get
			Set(ByVal value As System.String)
				OnTitleChanging(value)
				ReportPropertyChanging("Title")
				_Title = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Title")
				OnTitleChanged()
			End Set
		End Property
		Private _Title As Global.System.String
		Partial Private Sub OnTitleChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnTitleChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property FirstName() As Global.System.String
			Get
				Return _FirstName
			End Get
			Set(ByVal value As System.String)
				If _FirstName <> value Then
					OnFirstNameChanging(value)
					ReportPropertyChanging("FirstName")
					_FirstName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("FirstName")
					OnFirstNameChanged()
				End If
			End Set
		End Property
		Private _FirstName As Global.System.String
		Partial Private Sub OnFirstNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnFirstNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property MiddleName() As Global.System.String
			Get
				Return _MiddleName
			End Get
			Set(ByVal value As System.String)
				OnMiddleNameChanging(value)
				ReportPropertyChanging("MiddleName")
				_MiddleName = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("MiddleName")
				OnMiddleNameChanged()
			End Set
		End Property
		Private _MiddleName As Global.System.String
		Partial Private Sub OnMiddleNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnMiddleNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property LastName() As Global.System.String
			Get
				Return _LastName
			End Get
			Set(ByVal value As System.String)
				If _LastName <> value Then
					OnLastNameChanging(value)
					ReportPropertyChanging("LastName")
					_LastName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("LastName")
					OnLastNameChanged()
				End If
			End Set
		End Property
		Private _LastName As Global.System.String
		Partial Private Sub OnLastNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnLastNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Suffix() As Global.System.String
			Get
				Return _Suffix
			End Get
			Set(ByVal value As System.String)
				OnSuffixChanging(value)
				ReportPropertyChanging("Suffix")
				_Suffix = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Suffix")
				OnSuffixChanged()
			End Set
		End Property
		Private _Suffix As Global.System.String
		Partial Private Sub OnSuffixChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnSuffixChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property JobTitle() As Global.System.String
			Get
				Return _JobTitle
			End Get
			Set(ByVal value As System.String)
				If _JobTitle <> value Then
					OnJobTitleChanging(value)
					ReportPropertyChanging("JobTitle")
					_JobTitle = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("JobTitle")
					OnJobTitleChanged()
				End If
			End Set
		End Property
		Private _JobTitle As Global.System.String
		Partial Private Sub OnJobTitleChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnJobTitleChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Phone() As Global.System.String
			Get
				Return _Phone
			End Get
			Set(ByVal value As System.String)
				OnPhoneChanging(value)
				ReportPropertyChanging("Phone")
				_Phone = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Phone")
				OnPhoneChanged()
			End Set
		End Property
		Private _Phone As Global.System.String
		Partial Private Sub OnPhoneChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property EmailAddress() As Global.System.String
			Get
				Return _EmailAddress
			End Get
			Set(ByVal value As System.String)
				OnEmailAddressChanging(value)
				ReportPropertyChanging("EmailAddress")
				_EmailAddress = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("EmailAddress")
				OnEmailAddressChanged()
			End Set
		End Property
		Private _EmailAddress As Global.System.String
		Partial Private Sub OnEmailAddressChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnEmailAddressChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property EmailPromotion() As Global.System.Int32
			Get
				Return _EmailPromotion
			End Get
			Set(ByVal value As System.Int32)
				If _EmailPromotion <> value Then
					OnEmailPromotionChanging(value)
					ReportPropertyChanging("EmailPromotion")
					_EmailPromotion = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("EmailPromotion")
					OnEmailPromotionChanged()
				End If
			End Set
		End Property
		Private _EmailPromotion As Global.System.Int32
		Partial Private Sub OnEmailPromotionChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnEmailPromotionChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property AddressLine1() As Global.System.String
			Get
				Return _AddressLine1
			End Get
			Set(ByVal value As System.String)
				If _AddressLine1 <> value Then
					OnAddressLine1Changing(value)
					ReportPropertyChanging("AddressLine1")
					_AddressLine1 = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("AddressLine1")
					OnAddressLine1Changed()
				End If
			End Set
		End Property
		Private _AddressLine1 As Global.System.String
		Partial Private Sub OnAddressLine1Changing(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnAddressLine1Changed()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property AddressLine2() As Global.System.String
			Get
				Return _AddressLine2
			End Get
			Set(ByVal value As System.String)
				OnAddressLine2Changing(value)
				ReportPropertyChanging("AddressLine2")
				_AddressLine2 = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("AddressLine2")
				OnAddressLine2Changed()
			End Set
		End Property
		Private _AddressLine2 As Global.System.String
		Partial Private Sub OnAddressLine2Changing(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnAddressLine2Changed()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property City() As Global.System.String
			Get
				Return _City
			End Get
			Set(ByVal value As System.String)
				If _City <> value Then
					OnCityChanging(value)
					ReportPropertyChanging("City")
					_City = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("City")
					OnCityChanged()
				End If
			End Set
		End Property
		Private _City As Global.System.String
		Partial Private Sub OnCityChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property StateProvinceName() As Global.System.String
			Get
				Return _StateProvinceName
			End Get
			Set(ByVal value As System.String)
				If _StateProvinceName <> value Then
					OnStateProvinceNameChanging(value)
					ReportPropertyChanging("StateProvinceName")
					_StateProvinceName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("StateProvinceName")
					OnStateProvinceNameChanged()
				End If
			End Set
		End Property
		Private _StateProvinceName As Global.System.String
		Partial Private Sub OnStateProvinceNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnStateProvinceNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property PostalCode() As Global.System.String
			Get
				Return _PostalCode
			End Get
			Set(ByVal value As System.String)
				If _PostalCode <> value Then
					OnPostalCodeChanging(value)
					ReportPropertyChanging("PostalCode")
					_PostalCode = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("PostalCode")
					OnPostalCodeChanged()
				End If
			End Set
		End Property
		Private _PostalCode As Global.System.String
		Partial Private Sub OnPostalCodeChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property CountryRegionName() As Global.System.String
			Get
				Return _CountryRegionName
			End Get
			Set(ByVal value As System.String)
				If _CountryRegionName <> value Then
					OnCountryRegionNameChanging(value)
					ReportPropertyChanging("CountryRegionName")
					_CountryRegionName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("CountryRegionName")
					OnCountryRegionNameChanged()
				End If
			End Set
		End Property
		Private _CountryRegionName As Global.System.String
		Partial Private Sub OnCountryRegionNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCountryRegionNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property AdditionalContactInfo() As Global.System.String
			Get
				Return _AdditionalContactInfo
			End Get
			Set(ByVal value As System.String)
				OnAdditionalContactInfoChanging(value)
				ReportPropertyChanging("AdditionalContactInfo")
				_AdditionalContactInfo = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("AdditionalContactInfo")
				OnAdditionalContactInfoChanged()
			End Set
		End Property
		Private _AdditionalContactInfo As Global.System.String
		Partial Private Sub OnAdditionalContactInfoChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnAdditionalContactInfoChanged()
		End Sub

		#End Region

	End Class

	#End Region

End Namespace
